name: demo_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  firebase_core: ^1.22.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^4.18.3
  dependency_validator: ^3.2.2
  # flutter_test:
  #   sdk: flutter

flutter:
  uses-material-design: true
  generate: true # This line is required to generate the localization files
