name: flutter_dashboard_demo

packages:
  - apps/**
  - packages/**

scripts:
  # Dependencies
  pub:get:
    run: |
      dart pub global run melos exec --fail-fast --  "flutter pub get"
    description: Run `pub get` in all the packages

  gen_l10n:
    run: |
      dart pub global run melos exec --fail-fast -- \
        flutter gen-l10n
    description: Run `flutter gen-l10n` for a specific package.
    select-package:
      depends-on: flutter_localizations

  # Quality - lint
  lint:all:
    run: |
      dart pub global run melos run lint:analyze --no-select && \
      dart pub global run melos run lint:dependency --no-select && \
      dart pub global run melos run lint:format:check --no-select
    description: Run all static analysis checks.

  lint:analyze:
    run: |
      dart pub global run melos exec --fail-fast -- \
        flutter analyze . --fatal-infos --no-pub
    description: |
      Run `flutter analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  lint:dependency:
    run: |
      dart pub global run melos exec --fail-fast -- \
        flutter pub run dependency_validator
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  lint:format:check:
    run: |
      dart pub global run melos exec --fail-fast -- \
        dart format -o none --summary none --set-exit-if-changed .
    description: |
      Format all check.

  lint:format:
    run: |
      dart pub global run melos exec --fail-fast -- \
        dart format .
    description: |
      Format all.

  # Quality - metrics
  metrics:all:
    run: |
      dart pub global run melos run metrics:analyze --no-select && \
      dart pub global run melos run metrics:unused:code --no-select && \
      dart pub global run melos run metrics:unused:files --no-select && \
      dart pub global run melos run metrics:unnecessary:nullable --no-select
    description: Run all static analysis checks.
    
  metrics:analyze:
    run: |
      dart pub global run melos exec --fail-fast -- \
        flutter pub run dart_code_metrics:metrics analyze lib --fatal-style --fatal-performance --fatal-warnings --set-exit-on-violation-level=warning
    description: Run all static analysis checks.

  metrics:unused:code:
    run: |
      dart pub global run melos exec --fail-fast -- \
        flutter pub run dart_code_metrics:metrics check-unused-code lib --fatal-unused
    description: Run all static analysis checks.

  metrics:unused:files:
    run: |
      dart pub global run melos exec --fail-fast -- \
        flutter pub run dart_code_metrics:metrics check-unused-files lib --fatal-unused
    description: Run all static analysis checks.

  metrics:unnecessary:nullable:
    run: |
      dart pub global run melos exec --fail-fast -- \
        flutter pub run dart_code_metrics:metrics check-unnecessary-nullable lib --fatal-found
    description: Run all static analysis checks.

  # tests
  test:update_goldens:
    run: |
      rm -rf `find . -type d -name goldens` && \
      rm -rf `find . -type d -name failures` && \
      rm -rf `find . -type f -name coverage_test.dart` && \
      melos exec --fail-fast --depends-on=alchemist -- \
        flutter test --update-goldens --tags=golden > /dev/null
    description: Run `flutter test --update-goldens --tags=golden` for a specific package.

  test:golden_only:
    run: |
      dart pub global run melos exec --fail-fast -- \
        "flutter test --coverage --coverage-path=./coverage/\$MELOS_PACKAGE_NAME.lcov.info --tags=golden --dart-define=CI=$CI"
    description: Run all tests on golden projects.
    select-package:
      dir-exists:
        - test
      scope:
        - design_components
        
  post_clean: >
    dart pub global run melos exec -- "flutter clean"