name: design_theme
description: A new Flutter package project.
version: 0.0.1
homepage: dashboard_demo.com

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^4.18.3
  dependency_validator: ^3.2.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: pingfang
      fonts:
        - asset: fonts/pingfang/PingFang-SC-Bold.ttf
        - asset: fonts/pingfang/PingFang-SC-Light.ttf
        - asset: fonts/pingfang/PingFang-SC-Regular.ttf
